[package]
name = "vreg"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "vreg"
test = false
bench = false

[dependencies]
vespertine-rt = { path = "../../lib/vespertine-rt" }
vespertine-abi = { path = "../../lib/vespertine-abi" }
vespertine-std = { path = "../../lib/vespertine-std" }
config = { package = "vespertine-config", path = "../../lib/vespertine-config" }
