[package]
name = "vespertine-config"
version = "0.1.0"
edition = "2024"

[lib]
test = false
bench = false

[dependencies]
serde = { version = "1.0.228", default-features = false, features = ["derive", "alloc"] }
toml = { version = "1.1.2", default-features = false, features = ["serde", "parse"] }

[lints]
workspace = true
