[workspace]
members = [
    "kernel",
    "lib/vespertine-abi",
    "lib/vespertine-common",
    "lib/vespertine-rt", 
    "lib/vespertine-std", 
    "lib/vespertine-cli",
    "userland/dt", 
    "userland/dusk", 
    "userland/hesper", 
    "userland/ns", 
    "userland/terminal", "userland/stream", "userland/table", "userland/sys", "userland/nyx", "userland/vreg", "lib/vk-hal", "lib/vespertine-config", "userland/details", "userland/select", "userland/auth",
    "userland/vlog", "lib/vespertine-app",
]

resolver = "2"

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "z"     
lto = true          
codegen-units = 1   
panic = "abort"     
strip = false        
debug = true

[workspace.lints.rust]
dead_code = "allow"
