pub const AUTH_DEFAULT_USER_REQUEST: u32 = 0x4B00;
pub const AUTH_DEFAULT_USER_RESPONSE: u32 = 0x4B01;

pub const AUTH_LOOKUP_ID_REQUEST: u32 = 0x4B10;
pub const AUTH_LOOKUP_NAME_REQUEST: u32 = 0x4B11;
pub const AUTH_LOOKUP_RESPONSE: u32 = 0x4B12;

pub const AUTH_STATUS_OK: u32 = 0;
pub const AUTH_STATUS_NOT_FOUND: u32 = 1;
pub const AUTH_STATUS_INVALID_REQUEST: u32 = 2;
pub const AUTH_STATUS_INTERNAL_ERROR: u32 = 3;
