[package]
name = "kernel"
version = "0.1.0"
edition = "2024"

[lints.rust]
dead_code = "allow"

[[bin]]
name = "kernel"
test = false
bench = false

[dependencies]
async-trait = "0.1.89"
limine = "0.6.3"
simple-psf = "0.1.2"
vespertine-abi = { path = "../lib/vespertine-abi/" }
vespertine-common = { path = "../lib/vespertine-common/" }
hal = { package = "vk-hal", path = "../lib/vk-hal/" }
