version = 1 

[[application]]
id = "core.vespertine.stream"
bundle = "/Programs/stream.app"
default-entrypoint = "main"

[application.aliases]
stream = "main"

[installation]
installed-ts = 2026-06-26T19:00:00Z
updated-ts = 2026-06-26T19:00:00Z
