version = 1 

[[application]]
id = "core.vespertine.nyx"
bundle = "/Programs/nyx.app"
default-entrypoint = "main"

[application.aliases]
nyx = "main"

[installation]
installed-ts = 2026-06-27T04:42:34Z
updated-ts = 2026-06-27T04:42:34Z
