version = 1 

[[application]]
id = "core.vespertine.ns"
bundle = "/Programs/ns.app"
default-entrypoint = "main"

[application.aliases]
ns = "main"

[installation]
installed_ts = 2026-06-26T19:00:00Z
updated_ts = 2026-06-26T19:00:00Z
