version = 1 

[[application]]
id = "core.vespertine.dt"
bundle = "/Programs/dt.app"
default-entrypoint = "main"

[application.aliases]
dt = "main"

[installation]
installed-ts = 2026-06-26T19:00:00Z
updated-ts = 2026-06-26T19:00:00Z
