version = 1 

[[application]]
id = "core.vespertine.sys"
bundle = "/Programs/sys.app"
default-entrypoint = "main"

[application.aliases]
sys = "main"

[installation]
installed_ts = 2026-06-26T19:00:00Z
updated_ts = 2026-06-26T19:00:00Z
