version = 1 

[[application]]
id = "os.vespertine.terminal"
bundle = "/Programs/terminal.app"
default-entrypoint = "main"

[application.aliases]
terminal = "main"

[installation]
installed-ts = 2026-06-26T19:00:00Z
updated-ts = 2026-06-26T19:00:00Z
