version = 1 

[[application]]
id = "ports.openbsd.ls"
bundle = "/Programs/ls.app"
default-entrypoint = "main"

[application.aliases]
ls = "main"

[installation]
installed_ts = 2026-06-26T19:00:00Z
updated_ts = 2026-06-26T19:00:00Z
