version = 1 

[[application]]
id = "ports.0xAether.cowsay"
bundle = "/Programs/cowsay.app"
default-entrypoint = "main"

[application.aliases]
cowsay = "main"

[installation]
installed-ts = 2026-06-26T19:00:00Z
updated-ts = 2026-06-26T19:00:00Z
