[package]
name = "dusk"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "dusk"
test = false
bench = false

[dependencies]
vrt = { package = "vespertine-rt", path = "../../lib/vespertine-rt" }
vabi = { package = "vespertine-abi", path = "../../lib/vespertine-abi" }
vstd = { package = "vespertine-std", path = "../../lib/vespertine-std" }
vapp = { package = "vespertine-app", path = "../../lib/vespertine-app" }
